# Self-Hosted Github Action Runners on DigitalOcean via Cirun.io
# Reference: https://docs.cirun.io/Reference/yml.html
# Simple example via https://docs.cirun.io/reference/examples
runners:
  - name: "do-runner"
    # Cloud Provider: DigitalOcean
    cloud: "digitalocean"
    # Cheapest VM on DigitalOcean
    instance_type: "s-1vcpu-1gb"
    # Ubuntu-20.4  image"
    machine_image: "docker-20-04"
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-do-runner"
